# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - 386
      - amd64
    main: ./cmd/grpc-rpf
dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "quay.io/hchirino/grpc-rpf:latest"
      - "quay.io/hchirino/grcp-rpf:{{.Version}}"

archives:
  - replacements:
      darwin: mac
      386: 32bit-x86
      amd64: 64bit-x86

    format_overrides:
      - goos: windows
        format: zip
checksum:
  name_template: "checksums.txt"
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
