apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "chart.fullname" . }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  serviceName: {{ include "chart.fullname" . }}
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
  {{- include "chart.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
    {{- include "chart.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "chart.serviceAccountName" . }}
      securityContext:
      {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
          {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            - /usr/local/bin/grpc-rpf
            - server
            - "--listen=:8443"
            - --ca-file=/etc/grpc-rpf/ca.crt
            - --crt-file=/etc/grpc-rpf/tls.crt
            - --key-file=/etc/grpc-rpf/tls.key
            - --store-type=postgresql
          env:
            - name: GRPC_RPF_POSTGRESQL_HOST
              value: grpc-rpf-postgresql
            - name: GRPC_RPF_POSTGRESQL_PORT
              value: "5432"
            - name: GRPC_RPF_POSTGRESQL_SSLMODE
              value: disable
            - name: GRPC_RPF_POSTGRESQL_DATABASE
              value: {{ .Values.postgresql.postgresqlDatabase | quote }}
            - name: GRPC_RPF_POSTGRESQL_USER
              value: {{ .Values.postgresql.postgresqlUsername | quote }}
            - name: GRPC_RPF_POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "chart.fullname" . }}-postgresql
                  key: postgresql-password
            - name: GRPC_RPF_ADVERTISED_ADDRESS
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
          ports:
            - name: grpc
              containerPort: 8443
              protocol: TCP
          {{/*          livenessProbe:*/}}
          {{/*            httpGet:*/}}
          {{/*              path: /*/}}
          {{/*              port: http*/}}
          {{/*          readinessProbe:*/}}
          {{/*            httpGet:*/}}
          {{/*              path: /*/}}
          {{/*              port: http*/}}
          volumeMounts:
            - name: config
              mountPath: /etc/grpc-rpf
              readOnly: true
          resources:
      {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: config
          secret:
            secretName: {{ include "chart.fullname" . }}

      {{- with .Values.nodeSelector }}
      nodeSelector:
      {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
      {{- toYaml . | nindent 8 }}
      {{- end }}

      {{- with .Values.tolerations }}
      tolerations:
  {{- toYaml . | nindent 8 }}
  {{- end }}
