{{- $fullName := include "chart.fullname" . -}}
  {{- $Values := .Values -}}
  {{- $labels := include "chart.labels" . | nindent 4 -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $fullName }}
  labels:
  {{- $labels -}}
  {{- with $Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: "{{ $Values.ingress.hostname }}"
  to:
    kind: Service
    name: {{ $fullName }}
  port:
    targetPort: {{ $Values.service.port }}
  tls:
    termination: passthrough

  {{range $i, $e := until (int .Values.autoscaling.maxReplicas)}}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: "{{ $fullName }}-{{$i}}"
  labels:
  {{- $labels -}}
  {{- with $Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: "{{ $fullName }}-{{$i}}.{{ $Values.ingress.hostname }}"
  to:
    kind: Service
    name: "{{ $fullName }}-{{$i}}"
  port:
    targetPort: {{ $Values.service.port }}
  tls:
    termination: passthrough
  {{end}}
