{{- $fullName := include "chart.fullname" . -}}
  {{- $Values := .Values -}}
  {{- $labels := include "chart.labels" . | nindent 4 -}}
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $fullName }}
  labels:
  {{- $labels -}}
  {{- with $Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: "{{ $Values.ingress.hostname }}"
  to:
    kind: Service
    name: {{ $fullName }}
    weight: 100
  port:
    targetPort: 8443
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None

  {{range $i, $e := until (int .Values.autoscaling.maxReplicas)}}
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ $fullName }}- {{$i}}
  labels:
  {{- $labels -}}
  {{- with $Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  host: "{{ $fullName }}-{{$i}}.{{ $Values.ingress.hostname }}"
  to:
    kind: Service
    name: {{ $fullName }}- {{$i}}
    weight: 100
  port:
    targetPort: 8443
  tls:
    termination: passthrough
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
  {{end}}
