apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- $ca := genCA "ca" 3650 }}
  {{- $wcprivate :=  printf "*.%s.%s.svc.cluster.local"  (include "chart.fullname" .) .Release.Namespace }}
  {{- $wcpublic :=  printf "*.%s"  .Values.ingress.hostname }}
  {{- $cert := genSignedCert .Values.ingress.hostname  nil (list .Values.ingress.hostname $wcprivate $wcpublic) 3650 $ca }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
