{{- $ca := genCA "ca" 3650 }}
  {{- $fullName := include "chart.fullname" . }}
  {{- $hostname := .Values.ingress.hostname }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ $fullName }}
  namespace: {{ .Release.Namespace }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
type: kubernetes.io/tls
data:
  {{- $alternateDNS := list $hostname }}
  {{- range $i, $e := until (int .Values.autoscaling.maxReplicas) }}
  {{- $item := printf "%s-%d.%s"  $fullName $i $hostname }}
  {{- $alternateDNS = append $alternateDNS $item }}
  {{- end }}
  {{- $cert := genSignedCert .Values.ingress.hostname  nil  $alternateDNS 3650 $ca }}
  ca.crt: {{ $ca.Cert | b64enc | quote }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}
