{{- $fullName := include "chart.fullname" . -}}
  {{- $Values := .Values -}}
  {{- $labels := include "chart.labels" . | nindent 4 -}}
  {{- $selectorLabels := include "chart.selectorLabels" . | nindent 4 -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
  {{- include "chart.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: {{ $Values.service.port }}
  selector:
  {{- $selectorLabels }}

  {{range $i, $e := until (int .Values.autoscaling.maxReplicas)}}
---
apiVersion: v1
kind: Service
metadata:
  name: "{{ $fullName }}-{{$i}}"
  labels:
  {{- $labels -}}
  {{- with $Values.ingress.annotations }}
  annotations:
  {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 443
      targetPort: {{ $Values.service.port }}
  selector:
    statefulset.kubernetes.io/pod-name: "{{ $fullName }}-{{$i}}"
  {{- $selectorLabels }}
  {{end}}
