name: Release

on:
  push:
    tags:
      - '*'

jobs:
  goreleaser:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Get dependencies
        run: |
          go get -v -t -d ./...

      - name: Test
        run: go test -v ./...

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: hchirino
          password: ${{ secrets.QUAYIO_TOKEN }}

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          QUAY_TOKEN: ${{ secrets.GITHUB_TOKEN }}